/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 ./source/Vincent/scene.gltf -T --shadows
Author: TastyTony (https://sketchfab.com/TastyTony)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-glock-17-e341eb39f35e4690a051d181e9939280
Title: Low-Poly Glock 17
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Cube001_Material_0.geometry} material={materials.Material} skeleton={nodes.Cube001_Material_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material007_0.geometry} material={materials['Material.007']} skeleton={nodes.Cube001_Material007_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material009_0.geometry} material={materials['Material.009']} skeleton={nodes.Cube001_Material009_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material010_0.geometry} material={materials['Material.010']} skeleton={nodes.Cube001_Material010_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material004_0.geometry} material={materials['Material.004']} skeleton={nodes.Cube001_Material004_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material006_0.geometry} material={materials['Material.006']} skeleton={nodes.Cube001_Material006_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material005_0.geometry} material={materials['Material.005']} skeleton={nodes.Cube001_Material005_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material008_0.geometry} material={materials['Material.008']} skeleton={nodes.Cube001_Material008_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material002_0.geometry} material={materials['Material.002']} skeleton={nodes.Cube001_Material002_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material003_0.geometry} material={materials['Material.003']} skeleton={nodes.Cube001_Material003_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
      <skinnedMesh geometry={nodes.Cube001_Material001_0.geometry} material={materials['Material.001']} skeleton={nodes.Cube001_Material001_0.skeleton} position={[-205.406, 127.755, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
